#ci.yml is a yaml file(configuration file means setting or instructions for a file) instruction that tell automatically tell system what to do when u push code [yaml or yml both r same : yet another markup language] we use yaml file format coz it fits automation perfectly.
 #identation and spellings are vry imp doesnt get updated in workfloww
 #echo means print the text in terminal or command line interface
 #building an simple CI(continuous integration) pipeline that will run automatically when we push code to main branch using github actions.
 #virtual machine:A temporary cloud-based Linux system (Ubuntu) is automatically created by GitHub Actions to execute the CI pipeline steps, and it is deleted after execution
 #GitHub Actions, when a workflow is triggered, GitHub automatically creates a temporary Ubuntu-based virtual machine (runner) in its cloud environment to execute the pipeline steps defined in the ci.yml file. ocz they cannot run on their own  they need a 
name: Simple CI Pipeline 

on:
    push:
       branches: ["main"]
    pull_request:
       branches: ["main"]
       

jobs:
 build:
  runs-on: ubuntu-latest
  permissions:
    contents: read
    packages: write

  steps:
   - name: Checkout repository    
     uses: actions/checkout@v3

   - name: step 1
     run: echo "This is my ci.yml automated pipeline run"
   - name: step 2
     run: echo "This is my second step"
   - name: breaking step
     run: echo "pipeline is fixed now"
   - name: login to ghcr
     run: echo "${{ secrets.SHREE_1645 }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

   - name: build a docker image
     run: docker build -t ghcr.io/${{ github.actor }}/devops:v1 .

   - name: docker push
     run: docker push ghcr.io/${{ github.actor }}/devops:v1